### ISSUE TITLE
Extension does not launch parlatype from libreoffice

### ISSUE THREAD

**Issue by mbousq** [gkarsay/parlatype-libreoffice-extension#8]
Hi. The extension does not work in my hands using the the flatpak version of parlatype.

OS: ubuntu 21.10
Libre-office: 7.3.2.2

Any idea ? I am trying to get started with the automatic speech recognition. Thanks for this app !

**Comment by gkarsay** [comment]
Thanks for your report! That's a bug, in fact a regression that I didn't notice, introduced with commit a96f5b4dce32c78c162fcf7630ad1b04228eb014. It affects only the flatpak version of Parlatype.

**Comment by mbousq** [comment]
Many thanks  @gkarsay for following up on this :100:
